# 0517 DataNormalization

规范化分类的三种方法参考
https://www.geeksforgeeks.org/data-normalization-in-data-mining/?ref=lbp

## 数据转换 transformation

### 规范化

In [63]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from sklearn import datasets
from sklearn import preprocessing
from sklearn.preprocessing import Binarizer
from sklearn.decomposition import PCA

In [9]:
        #boston
        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]
        type(target)

numpy.ndarray

In [14]:
#california housing dataset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
type(housing)

sklearn.utils.Bunch

In [16]:
housing.data.shape

(20640, 8)

In [17]:
#哪几个属性
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [18]:
#目标属性：房价中位数
housing.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [36]:
#切片
df = pd.DataFrame(housing.data[:,2:5])
df.columns = housing.feature_names[2:5]
df

AveRooms  AveBedrms  Population
0      6.984127   1.023810       322.0
1      6.238137   0.971880      2401.0
2      8.288136   1.073446       496.0
3      5.817352   1.073059       558.0
4      6.281853   1.081081       565.0
...         ...        ...         ...
20635  5.045455   1.133333       845.0
20636  6.114035   1.315789       356.0
20637  5.205543   1.120092      1007.0
20638  5.329513   1.171920       741.0
20639  5.254717   1.162264      1387.0

[20640 rows x 3 columns]

In [28]:
# 最小-最大规范化
## 用公式
df1= (df-df.min())/(df.max()-df.min())
# df1
## 用preprocessing模块
df2=preprocessing.minmax_scale(df)
df2
######################函数##########################################
def MinMax_Norm(df):
    df_normed = preprocessing.minmax_scale(df)
    return df_normed
df_norm_test = MinMax_Norm(df)
df_norm_test


array([[0.0435123 , 0.02046866, 0.00894083],
       [0.03822395, 0.01892926, 0.0672104 ],
       [0.05275646, 0.02194011, 0.01381765],
       ...,
       [0.03090386, 0.0233229 , 0.0281398 ],
       [0.03178269, 0.02485928, 0.02068444],
       [0.03125246, 0.02457305, 0.03879032]])

In [32]:
# zscore 规范化
## 公式处理
df3=(df-df.mean())/df.std()
#df3
## preprocessing模块处理
df4=preprocessing.scale(df)
df4
######################函数##########################################
def Zscore_Norm(df):
    df_normed = preprocessing.scale(df)
    return df_normed
df_norm_test2 = Zscore_Norm(df)
df_norm_test2

array([[ 0.62855945, -0.15375759, -0.9744286 ],
       [ 0.32704136, -0.26333577,  0.86143887],
       [ 1.15562047, -0.04901636, -0.82077735],
       ...,
       [-0.09031802,  0.04941393, -0.3695372 ],
       [-0.04021111,  0.15877763, -0.60442933],
       [-0.07044252,  0.1384028 , -0.03397701]])

In [34]:
# 小数定标规范化
## 公式处理
df5=df/10**np.ceil(np.log10(df.abs().max()))
#df5
######################函数##########################################
def Decimal_Norm(df):
    df_normed = df/10**np.ceil(np.log10(df.abs().max()))
    return df_normed
df_norm_test3 = Decimal_Norm(df)
#df_norm_test3

### 连续属性离散化

In [40]:
pd.cut(df.Population,20,labels=range(20))

0        0
1        1
2        0
3        0
4        0
        ..
20635    0
20636    0
20637    0
20638    0
20639    0
Name: Population, Length: 20640, dtype: category
Categories (20, int64): [0 < 1 < 2 < 3 ... 16 < 17 < 18 < 19]

In [41]:
pd.qcut(df.Population,20,labels=range(20))

0         0
1        17
2         1
3         2
4         2
         ..
20635     5
20636     1
20637     7
20638     4
20639    12
Name: Population, Length: 20640, dtype: category
Categories (20, int64): [0 < 1 < 2 < 3 ... 16 < 17 < 18 < 19]

In [58]:
# df.Population
# type(df.Population)
# df.iloc[:,1]
# df_binned = pd.qcut(df.iloc[:,1],20,labels=range(20))

def Binning(col_Index):
    df_binned = pd.qcut(df.iloc[:,col_Index],20,labels=range(20))
    return df_binned
df6=Binning(1)
df6

0         6
1         2
2        12
3        12
4        13
         ..
20635    16
20636    19
20637    16
20638    17
20639    17
Name: AveBedrms, Length: 20640, dtype: category
Categories (20, int64): [0 < 1 < 2 < 3 ... 16 < 17 < 18 < 19]

### 特征二值化

prerprossessing模块中Binarizer()或LabelEncoder()函数

In [60]:
X=housing.target.reshape(-1,1)
Binarizer(threshold=4).fit_transform(X)

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [62]:
type(X)#numpy.ndarray
type(housing.data)#numpy.ndarray
housing.target.shape
#housing target是1行20640列，要得到每条记录有一个类别，故需要有20640行/样本
housing.target.reshape(-1,1).shape

(20640, 1)

## 数据规约

### 属性规约，以PCA降维为例

In [80]:
housing.data
X

array([[ 2.34476576,  0.98214266,  0.62855945, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 2.33223796, -0.60701891,  0.32704136, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.7826994 ,  1.85618152,  1.15562047, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [-1.05458292, -0.84539315, -0.04021111, ..., -0.09122515,
         1.77823747, -0.87362627],
       [-0.78012947, -1.00430931, -0.07044252, ..., -0.04368215,
         1.75014627, -0.83369581]])

In [78]:
X= preprocessing.scale(housing.data)#标准化处理
#n_components设置为‘mle’，算法自动选择满足所要求的方差百分比的特征个数；设置为数字n，则对应n个特征
pca=PCA(n_components=3)
# pca=PCA(n_components='mle')
pca.fit(X)
pca.components_
#Principal axes in feature space, representing the directions of maximum variance in the data. Equivalently, the right singular vectors of the centered input data, parallel to its eigenvectors. 
#type(pca.components_)
# pca.n_components
#pca

array([[ 0.07746229,  0.00731846,  0.43914246,  0.3999956 , -0.17178267,
        -0.01464423,  0.56836442, -0.53697448],
       [ 0.22987873, -0.26078574,  0.54668689,  0.50184958,  0.10062559,
         0.00262099, -0.37401073,  0.4223868 ],
       [ 0.21822239, -0.6275508 , -0.06399944, -0.19184813,  0.65037482,
         0.15772711,  0.19259966, -0.18082441]])

In [ ]:
ratio = pca.explained_variance_ratio_#各成分方差百分比，各变量的方差贡献率
s=sum(ratio)
s
print("前"+"3"+"个属性解释了数据中"+str(s)+"的变化。")

In [81]:
def Reduction_pca(df,n='mle'):
    X= preprocessing.scale(df)#标准化处理
    #n_components设置为‘mle’，算法自动选择满足所要求的方差百分比的特征个数；设置为数字n，则对应n个特征
    pca=PCA(n_components=n)
    # pca=PCA(n_components='mle')
    pca.fit(X)
    pca_com=pca.components_
    ratio = pca.explained_variance_ratio_#各成分方差百分比，各变量的方差贡献率
    s=sum(ratio)
    print("前"+str(n)+"个属性解释了数据中"+str(s)+"的变化。")
    return pca_com
pca_components = Reduction_pca(housing.data,3)

前3个属性解释了数据中0.6474174722211659的变化。


### 数值规约，以简单随机抽样为例

In [87]:
#replace-true表示有放回；反之不放回
df.sample(n=20)
df.sample(frac=0.1)#frac为抽样百分比
def Simple_Sample(df,sam_num):
    df_sample=df.sample(n=sam_num)
    return df_sample
df_sample=Simple_Sample(df,5)
df_sample

AveRooms  AveBedrms  Population
9030   6.981132   1.089623      1560.0
19236  7.662162   1.114865       847.0
7859   4.309353   0.899281       361.0
13190  5.154062   1.064426      1187.0
10089  5.267760   0.983607      1056.0

### 分层抽样

In [89]:
iris=datasets.load_iris()
iris_df=pd.DataFrame(iris.data)
iris_df.columns = iris.feature_names
iris_df['target']=iris.target

In [95]:
A=iris_df[iris_df.target==0].sample(frac=0.2)
B=iris_df[iris_df.target==1].sample(frac=0.2)
df_new_sampled=A.append(B)
df_new_sampled

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
13                4.3               3.0                1.1               0.1   
5                 5.4               3.9                1.7               0.4   
25                5.0               3.0                1.6               0.2   
49                5.0               3.3                1.4               0.2   
23                5.1               3.3                1.7               0.5   
9                 4.9               3.1                1.5               0.1   
41                4.5               2.3                1.3               0.3   
4                 5.0               3.6                1.4               0.2   
32                5.2               4.1                1.5               0.1   
33                5.5               4.2                1.4               0.2   
96                5.7               2.9                4.2               1.3   
65                6.7               3.1                4.4               1.4   
76                6.8               2.8                4.8               1.4   
84                5.4               3.0                4.5               1.5   
80                5.5               2.4                3.8               1.1   
52                6.9               3.1                4.9               1.5   
77                6.7               3.0                5.0               1.7   
55                5.7               2.8                4.5               1.3   
59                5.2               2.7                3.9               1.4   
99                5.7               2.8                4.1               1.3   

    target  
13       0  
5        0  
25       0  
49       0  
23       0  
9        0  
41       0  
4        0  
32       0  
33       0  
96       1  
65       1  
76       1  
84       1  
80       1  
52       1  
77       1  
55       1  
59       1  
99       1

In [10]:
#ames housing dataset
from sklearn.datasets import fetch_openml
housing = fetch_openml(name="house_prices", as_frame=True)
type(housing)

sklearn.utils.Bunch

In [7]:
boston = datasets.load_boston()
boston

C:\ANACONDA3\envs\Simi_com\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [13]:
type(boston)
# boston.data.shape


sklearn.utils.Bunch

In [ ]:
boston.feature_names

In [ ]:
X_train = np.array([[ 1., -1.,  2.]])
type(X_train))

In [ ]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])


In [ ]:
X_scaled = preprocessing.scale(X_train)
X_scaled


In [ ]:
array([[ 0.  ..., -1.22...,  1.33...],
       [ 1.22...,  0.  ..., -0.26...],
       [-1.22...,  1.22..., -1.06...]])

经过缩放后的数据具有零均值以及标准方差:

```py
>>> X_scaled.mean(axis=0)
array([ 0.,  0.,  0.])

>>> X_scaled.std(axis=0)
array([ 1.,  1.,  1.])
